### ISSUE TITLE
Data Use should be Ontology_class Array

### ISSUE THREAD

**Issue by aaliomer** [ga4gh-metadata/SchemaBlocks#11]
In DUO, you are able to add secondary and primary use cases.
Also, you might want to add two or more data use cases (cancer and diabetes research for example)

If a biosample can have one data use code, should a biosample have more than one schemablock? thats a data management headache. having a set of data use codes instead of one might solve it

**Comment by mbaudis** [comment]
That's a good point. In principle, we could use the general way this is dome e.g. for `external_references` and `biocharacteristics`; having an array of `data_use_conditions`, where each consists of a reference-object (like) object:

```
"data_use_conditions":
  [
    {
      "description" : "study derived data use",
      "type": {
        "id": "DUO_0000003",
        "label": "genetic studies only"
      },
    },
    {
      "description" : "institutional data use policy",
      "type": {
        "id": "DUO:0000004",
        "label": "no restrictions"
      },
    },
  ]
```
Not sure if this is a good example; happy about others. 

But generally, I like the structure of those list objects, where one always can address a specific identifier through `my_attribute_name.type.id` (or in Perl etc. `$attributes->{my_attribute_name}->{type}->{id}`). 

Maybe @mcourtot can comment?

**Comment by mbaudis** [comment]
@aaliomer ... but we should actually start to move issues/discussions to the https://github.com/ga4gh-schemablocks/blocks/ repository. So maybe you can write this up there in more detail (including a draft proposal)?

**Comment by aaliomer** [comment]
I'll move it. but what is the difference between the two repositories?

**Comment by mbaudis** [comment]
@aaliomer This here is basically the GA4GH metadata schema (+ some changes) re-write in a more modular way; from this, we've now moved to have a "proper" SchemaBlocks initiative which should become the core of cross-schema GA4GH standards and objects documentation. For now, more definitions can be found here, but this is rapidly changing.

**Comment by mbaudis** [comment]
Moved to => https://github.com/ga4gh-schemablocks/blocks/issues/4
